package com.verumomnis.forensics.core;

/**
 * ForensicVersion - Version constants for Verum Omnis Forensic Engine
 * 
 * CONSTITUTIONAL REQUIREMENT:
 * Version MUST be v5.2.7 and included in all generated reports
 */
public class ForensicVersion {
    
    /**
     * Engine version - MUST NOT be changed
     * This is the constitutional version per the Verum Omnis Master Forensic Archive
     */
    public static final String ENGINE_VERSION = "v5.2.7";
    
    /**
     * Full engine name for reports
     */
    public static final String ENGINE_NAME = "Verum Omnis Forensic Engine";
    
    /**
     * Full report header
     */
    public static final String REPORT_HEADER = "Generated by " + ENGINE_NAME + " " + ENGINE_VERSION;
    
    /**
     * Build number (can increment for bug fixes without changing constitutional version)
     */
    public static final int BUILD_NUMBER = 1;
}
